export { anchorFor, foundAgain, rowsForRange } from "./anchor.ts"
export { parsePatches } from "./parse.ts"
export { stickyChain } from "./sticky.ts"
export { lineOn, WHOLE_FILE } from "./model.ts"
export type { Anchor, Hunk, Patch, Range, Row, RowKind, Side } from "./model.ts"
